apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  dsn: ZGV2X3VzZXI6S2FuaXNoa18yMkB0Y3AobXlzcWwtc2VydmljZTozMzA2KS9hdXRoX3NlcnZpY2VfZGI=
  JWTSECRET: amhzZiRXJSRxdDNyZWQ2Yg==
  JWTEXPIRY: "ODY0MDA="
